# Generated by Django 4.1.3 on 2022-12-11 19:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('newtspaper_app', '0002_remove_articles_favorite_articles_favorites'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articles',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
