# Generated by Django 4.1.3 on 2022-12-14 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newtspaper_app', '0005_alter_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='articles',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='articles',
            name='urlToImage',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
